### ISSUE TITLE
readVec of TextPrimIO.RD bug save_vec.cpp:70: SaveVecEntry* SaveVec::push(PolyWord): Assertion `save_vec_addr < save_vec+1000' failed.

### ISSUE THREAD

**Issue by h4kmw93v** [polyml/polyml#57] opened 2016-05-17 21:02 UTC
Here is a testcase:

fun main() =
    let
        val simpleReader = Posix.IO.mkTextReader {
                fd = Posix.FileSys.stdin,
                name = "simpleReader",
                initBlkMode = false
            }

        val TextPrimIO.RD { readVec, ... } = simpleReader
        val read = valOf readVec
    in
        read 1 ; ()
    end

Then compile with polyc, and run like:
echo x | ./a.out

Observed result:
a.out: save_vec.cpp:70: SaveVecEntry* SaveVec::push(PolyWord): Assertion `save_vec_addr < save_vec+1000' failed.
Aborted

Expected result:
One character is read into a vector and no assertion failure occurs.

The problem occurs as well in interactive 'poly' shell.

**Comment by dcjm** [comment] 2016-05-19 15:19
Which version of Poly/ML are you using?  I can't reproduce the problem with either the current release or git master.
David

**Comment by h4kmw93v** [comment] 2016-05-19 21:29
$ poly -v
Poly/ML 5.5.2 Release    RTS version: Portable-5.5.1

which is the latest version available in Gentoo now.

[ebuild   R   ~] dev-lang/polyml-5.5.2:0/5.5.2::gentoo  USE="portable threads -X -gmp {-test}" 0 KiB

In Gentoo PolyML is built from source during installation. The USE flags are mapped to configure flags. I tried also without 'portable', but didn't help.

Since the assertions has to do with addresses, it might be important that I'm running pure 64 bit system (Gentoo people call this no-multilib). This means I don't have any 32bit binaries/libraries.

$ uname -srvmpio
Linux 4.5.4-hardened-gnu #1 SMP PREEMPT Sun May 15 11:45:30 CEST 2016 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux

$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.5/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.8.5/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.8.5/work/gcc-4.8.5/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.5 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.8.5/python --enable-languages=c,c++,java --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --disable-nls --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 4.8.5 p1.3, pie-0.6.2' --enable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libquadmath --enable-lto --without-cloog --disable-libsanitizer
Thread model: posix
gcc version 4.8.5 (Gentoo Hardened 4.8.5 p1.3, pie-0.6.2)

I will have to wait and see what happens in PolyML 5.6 as soon as it's available in Gentoo.

**Comment by h4kmw93v** [comment] 2016-05-20 08:11
Workaround found. If I use block and readVecNB, it works. It's easy to apply to my own programs, and with more work to others' open-source programs. So please mark the issue as low priority.

**Comment by dcjm** [comment] 2016-05-20 10:17
As far as I'm aware this bug was fixed in 5.6.  That version was released in January so there's really no reason that Gentoo should still be distributing 5.5.2.  We have no control over how Poly/ML is packaged; the only official distribution is from the [Poly/ML website](www.polyml.org) or [github](http://www.polyml.org/download.html).  Could you please contact the packager and ask that the package be updated.  I'm closing this as fixed.
David

**Closed by dcjm** 2016-05-20 10:17 UTC
