### ISSUE TITLE
Dramatic slowdowns compared to 5.6

### ISSUE THREAD

**Issue by mn200** [polyml/polyml#69] opened 2016-11-11 04:11 UTC
Most recently tested against 9d84e44, but we've been observing this for a while.

When running our standard CI tests for HOL4, we're seeing dramatic slowdowns on execution of the system. See the timing figures at https://travis-ci.org/HOL-Theorem-Prover/HOL/builds/174934897 where sub-builds 7, 8 and 10 are all doing the same thing.  One is vanilla 5.6, one is 5.6 installed as root, and the last is pulling from GitHub to get the most recent commit.   (There is a factor of 4 involved.) 

Looking at where the problems arise, I'd guess that the issue may be compile-time in some part of our kernel rather than execution.  What was once very fast is turning into an 11 minute compile time. 

Once the relevant bits of code are stashed in a heap, the execution times look quite reasonable.  The following is effectively the sequence of `use` calls being made:

```
local val dir = OS.FileSys.getDir()
val _ = OS.FileSys.chDir "/Users/nor190/HOL/tools-poly";
val _ = use "poly/poly-init2.ML";
val _ = OS.FileSys.chDir dir in end;
use "/Users/nor190/HOL/src/prekernel/locn.sig";
use "/Users/nor190/HOL/src/prekernel/locn.sml";
use "/Users/nor190/HOL/src/prekernel/Feedback.sig";
use "/Users/nor190/HOL/src/portableML/HOLPP.sig";
use "/Users/nor190/HOL/src/portableML/UTF8.sig";
use "/Users/nor190/HOL/src/portableML/UTF8.sml";
use "/Users/nor190/HOL/src/portableML/HOLPP.sml";
use "/Users/nor190/HOL/src/portableML/poly/Arbnumcore.sig";
use "/Users/nor190/HOL/src/portableML/poly/Arbnumcore.sml";
use "/Users/nor190/HOL/src/portableML/Arbnum.sig";
use "/Users/nor190/HOL/src/portableML/Arbnum.sml";
use "/Users/nor190/HOL/src/portableML/Portable.sig";
use "/Users/nor190/HOL/src/portableML/poly/MD5.sig";
use "/Users/nor190/HOL/src/portableML/poly/MD5.sml";
use "/Users/nor190/HOL/src/portableML/poly/Susp.sig";
use "/Users/nor190/HOL/src/portableML/poly/Susp.sml";
use "/Users/nor190/HOL/src/portableML/poly/MLSYSPortable.sml";
use "/Users/nor190/HOL/src/portableML/Portable.sml";
use "/Users/nor190/HOL/src/prekernel/Globals.sig";
use "/Users/nor190/HOL/sigobj/Systeml.sig";
use "/Users/nor190/HOL/sigobj/Systeml.sml";
use "/Users/nor190/HOL/src/prekernel/Globals.sml";
use "/Users/nor190/HOL/src/prekernel/Feedback.sml";
use "/Users/nor190/HOL/src/prekernel/KernelSig.sig";
use "/Users/nor190/HOL/src/prekernel/KernelSig.sml";
use "/Users/nor190/HOL/src/prekernel/Dep.sig";
use "/Users/nor190/HOL/src/portableML/Redblackmap.sig";
use "/Users/nor190/HOL/src/portableML/Redblackmap.sml";
use "/Users/nor190/HOL/src/prekernel/Lib.sig";
use "/Users/nor190/HOL/src/prekernel/Lib.sml";
use "/Users/nor190/HOL/src/prekernel/Dep.sml";
use "/Users/nor190/HOL/src/prekernel/Nonce.sig";
use "/Users/nor190/HOL/src/prekernel/Nonce.sml";
use "/Users/nor190/HOL/src/prekernel/FinalTag-sig.sml";
use "/Users/nor190/HOL/src/portableML/Redblackset.sig";
use "/Users/nor190/HOL/src/portableML/Redblackset.sml";
use "/Users/nor190/HOL/src/prekernel/HOLset.sig";
use "/Users/nor190/HOL/src/prekernel/HOLset.sml";
use "/Users/nor190/HOL/src/prekernel/FinalTerm-sig.sml";
use "/Users/nor190/HOL/src/prekernel/FinalThm-sig.sml";
use "/Users/nor190/HOL/src/prekernel/FinalType-sig.sml";
use "/Users/nor190/HOL/src/prekernel/Tag.sig";
use "/Users/nor190/HOL/src/prekernel/Tag.sml";
use "/Users/nor190/HOL/src/0/Net-sig.sml";
use "/Users/nor190/HOL/src/0/Subst.sig";
use "/Users/nor190/HOL/src/0/Subst.sml";
use "/Users/nor190/HOL/src/0/KernelTypes.sig";
use "/Users/nor190/HOL/src/0/KernelTypes.sml";
use "/Users/nor190/HOL/src/0/Term.sig";
use "/Users/nor190/HOL/src/prekernel/Lexis.sig";
use "/Users/nor190/HOL/src/prekernel/Lexis.sml";
use "/Users/nor190/HOL/src/0/Type.sig";
use "/Users/nor190/HOL/src/0/Type.sml";
use "/Users/nor190/HOL/src/0/Term.sml";
use "/Users/nor190/HOL/src/0/Thm.sig";
use "/Users/nor190/HOL/src/prekernel/Count.sig";
use "/Users/nor190/HOL/src/prekernel/Count.sml";
use "/Users/nor190/HOL/src/0/Thm.sml";
use "/Users/nor190/HOL/src/0/CoreKernel-sig.sml";
use "/Users/nor190/HOL/src/0/Raw-sig.sml";
use "/Users/nor190/HOL/src/0/Net.sml";
use "/Users/nor190/HOL/src/0/Overlay.sml";
use "/Users/nor190/HOL/src/parse/GrammarSpecials.sig";
use "/Users/nor190/HOL/src/postkernel/TheoryDelta.sml";
use "/Users/nor190/HOL/src/postkernel/Theory.sig";
use "/Users/nor190/HOL/src/portableML/UniversalType.sig";
use "/Users/nor190/HOL/src/portableML/UniversalType.sml";
use "/Users/nor190/HOL/src/postkernel/TheoryPP.sig";
use "/Users/nor190/HOL/src/postkernel/SharingTables.sig";
use "/Users/nor190/HOL/src/postkernel/SharingTables.sml";
use "/Users/nor190/HOL/src/postkernel/TheoryPP.sml";
use "/Users/nor190/HOL/src/postkernel/Theory.sml";
use "/Users/nor190/HOL/src/postkernel/HolKernel.sml";
use "/Users/nor190/HOL/src/portableML/monads/optmonad.sig";
use "/Users/nor190/HOL/src/portableML/monads/optmonad.sml";
use "/Users/nor190/HOL/src/parse/Coding.sig";
use "/Users/nor190/HOL/src/parse/Coding.sml";
use "/Users/nor190/HOL/src/parse/GrammarSpecials.sml";
use "/Users/nor190/HOL/src/portableML/monads/errormonad.sig";
use "/Users/nor190/HOL/src/portableML/monads/errormonad.sml";
use "/Users/nor190/HOL/src/parse/Pretype_dtype.sml";
use "/Users/nor190/HOL/src/parse/base_tokens.sig";
use "/Users/nor190/HOL/src/parse/base_tokens.sml";
use "/Users/nor190/HOL/src/parse/qbuf.sig";
use "/Users/nor190/HOL/src/parse/MLstring.sig";
use "/Users/nor190/HOL/src/parse/MLstring.sml";
use "/Users/nor190/HOL/src/parse/base_lexer.sml";
use "/Users/nor190/HOL/src/parse/qbuf.sml";
use "/Users/nor190/HOL/src/parse/HOLgrammars.sml";
use "/Users/nor190/HOL/src/parse/TypeNet.sig";
use "/Users/nor190/HOL/src/parse/TypeNet.sml";
use "/Users/nor190/HOL/src/parse/type_grammar_dtype.sml";
use "/Users/nor190/HOL/src/parse/type_grammar.sig";
use "/Users/nor190/HOL/src/portableML/FunctionalRecordUpdate.sml";
use "/Users/nor190/HOL/src/parse/type_grammar.sml";
use "/Users/nor190/HOL/src/parse/parse_type.sig";
use "/Users/nor190/HOL/src/parse/type_tokens.sig";
use "/Users/nor190/HOL/src/portableML/UnicodeChars.sig";
use "/Users/nor190/HOL/src/portableML/UnicodeChars.sml";
use "/Users/nor190/HOL/src/parse/type_tokens.sml";
use "/Users/nor190/HOL/src/parse/parse_type.sml";
use "/Users/nor190/HOL/src/parse/typecheck_error.sml";
use "/Users/nor190/HOL/src/parse/Pretype.sig";
use "/Users/nor190/HOL/src/parse/Pretype.sml";
use "/Users/nor190/HOL/src/parse/Absyn_dtype.sml";
use "/Users/nor190/HOL/src/parse/Absyn.sig";
use "/Users/nor190/HOL/src/parse/Absyn.sml";
use "/Users/nor190/HOL/src/parse/LVTermNetFunctor.sml";
use "/Users/nor190/HOL/src/parse/Overload.sig";
use "/Users/nor190/HOL/src/portableML/monads/stmonad.sig";
use "/Users/nor190/HOL/src/portableML/monads/stmonad.sml";
use "/Users/nor190/HOL/src/parse/Overload.sml";
use "/Users/nor190/HOL/src/portableML/seq.sig";
use "/Users/nor190/HOL/src/portableML/seq.sml";
use "/Users/nor190/HOL/src/portableML/monads/seqmonad.sig";
use "/Users/nor190/HOL/src/portableML/monads/seqmonad.sml";
use "/Users/nor190/HOL/src/parse/Preterm_dtype.sml";
use "/Users/nor190/HOL/src/parse/Preterm.sig";
use "/Users/nor190/HOL/src/parse/Literal.sig";
use "/Users/nor190/HOL/src/parse/Literal.sml";
use "/Users/nor190/HOL/src/parse/Preterm.sml";
use "/Users/nor190/HOL/src/parse/Parse_supportENV.sml";
use "/Users/nor190/HOL/src/parse/term_grammar_dtype.sml";
use "/Users/nor190/HOL/src/parse/term_pp_types.sml";
use "/Users/nor190/HOL/src/parse/term_grammar.sig";
use "/Users/nor190/HOL/src/parse/term_grammar.sml";
use "/Users/nor190/HOL/src/parse/PPBackEnd.sig";
use "/Users/nor190/HOL/src/parse/PPBackEnd.sml";
use "/Users/nor190/HOL/src/parse/Parse.sig";
use "/Users/nor190/HOL/src/parse/GrammarAncestry.sig";
use "/Users/nor190/HOL/src/parse/GrammarAncestry.sml";
use "/Users/nor190/HOL/src/parse/GrammarDeltas.sig";
use "/Users/nor190/HOL/src/parse/GrammarDeltas.sml";
use "/Users/nor190/HOL/src/parse/ProvideUnicode.sig";
use "/Users/nor190/HOL/src/parse/ProvideUnicode.sml";
use "/Users/nor190/HOL/src/parse/Parse_support.sig";
use "/Users/nor190/HOL/src/parse/Parse_support.sml";
use "/Users/nor190/HOL/src/parse/TermParse.sig";
use "/Users/nor190/HOL/src/parse/parse_term_dtype.sml";
use "/Users/nor190/HOL/src/parse/parse_term.sig";
use "/Users/nor190/HOL/src/parse/term_tokens.sig";
use "/Users/nor190/HOL/src/portableML/UTF8Set.sig";
use "/Users/nor190/HOL/src/portableML/UTF8Set.sml";
use "/Users/nor190/HOL/src/parse/CharSet.sig";
use "/Users/nor190/HOL/src/parse/CharSet.sml";
use "/Users/nor190/HOL/src/parse/term_tokens.sml";
use "/Users/nor190/HOL/src/parse/parse_term.sml";
use "/Users/nor190/HOL/src/parse/TermParse.sml";
use "/Users/nor190/HOL/src/parse/smpp.sig";
use "/Users/nor190/HOL/src/parse/smpp.sml";
use "/Users/nor190/HOL/src/parse/term_pp.sig";
use "/Users/nor190/HOL/src/parse/HOLtokens.sig";
use "/Users/nor190/HOL/src/parse/HOLtokens.sml";
use "/Users/nor190/HOL/src/parse/term_pp_utils.sig";
use "/Users/nor190/HOL/src/parse/term_pp_utils.sml";
use "/Users/nor190/HOL/src/parse/type_pp.sig";
use "/Users/nor190/HOL/src/parse/type_pp.sml";
use "/Users/nor190/HOL/src/parse/term_pp.sml";
use "/Users/nor190/HOL/src/parse/Parse.sml";
use "/Users/nor190/HOL/src/bool/TexTokenMap.sig";
use "/Users/nor190/HOL/src/bool/TexTokenMap.sml";
```

I guess one of those files is causing the issue.  If I find time to isolate the file, I'll let you know which it is.

**Comment by dcjm** [comment] 2016-11-13 14:50
Thanks for reducing that to something that I could work with.  The problem is with the register allocation code in MD5.  I can see where the problem is but it will take a bit longer to come up with a fix.

**Comment by dcjm** [comment] 2016-11-13 16:30
I've now pushed a fix for this.  I'll close this.  Please reopen if there's still a problem.

**Closed by dcjm** 2016-11-13 16:30 UTC

**Comment by mn200** [comment] 2016-11-14 22:17
Thanks; that's dramatically better.  As per the [latest HOL commit regression test](https://travis-ci.org/HOL-Theorem-Prover/HOL/builds/175663706), the same test case is now taking 15 minutes compared to 5.6's 12 minutes.  (It used to be 47 minutes.)
