### ISSUE TITLE
5.6 Testing: potential assertion error in libpolyml/processes.cpp

### ISSUE THREAD

**Issue by Hibou57** [polyml/polyml#9] opened 2015-12-30 07:49 UTC
Trying to build HOL4 with Poly/ML from trunk (Poly/ML 5.6 Testing), I encountered this error:

    unquote: ../../polyml.git/trunk/libpolyml/processes.cpp:712: virtual void Processes::ThreadExit(TaskData*): Assertion `index < taskArraySize && taskArray[index] == taskData' failed.
    Aborted (core dumped)

Please, note Poly/ML was build with the `--with-portable` option, although I don't know if this assertion error is related or not.

Original bug reported as an HOL4 build issue, here: (Build failure with PolyML 5.6)[https://github.com/HOL-Theorem-Prover/HOL/issues/323).

**Comment by dcjm** [comment] 2015-12-30 13:23
This looks like a problem with the interpreted version. I've fixed a bug with Thread.Thread.exit in the interpreted version but it produced a segfault rather than an assertion fault.  It's likely it's the same bug. I'm going to close this but please reopen if it is still present especially if it shows up in the native code version.

**Closed by dcjm** 2015-12-30 13:23 UTC

**Comment by jrtc27** [comment] 2016-02-01 17:24
I just ran into this as maintainer of the Debian package; https://buildd.debian.org/status/fetch.php?pkg=polyml&arch=ppc64el&ver=5.6-2&stamp=1454346847 has the log for the failing build on ppc64el. My previous upload (5.6-1) built fine on ppc64el, and this version built on ppc64, so I don't imagine it's down to any of the additional patches I backported, although that's always a possibility.

**Comment by dcjm** [comment] 2016-02-10 16:15
I've been looking into this although not on the ppc64.  Is this reproducible or is it random?  I'm inclined to think there's a timing issue with the interpreted version.  It's never been reported in the X86 native code versions.

**Comment by jrtc27** [comment] 2016-02-10 16:25
It's not very reproducible as it was rerun the next day and succeeded. I've only seen it occur that one time, and doubt it's specific to ppc64el (which is a 64-bit little-endian architecture and thus not much different from running an interpreted amd64 version).

**Comment by jrtc27** [comment] 2016-04-12 16:27
Reproducible on amd64 using the current master (g1e230f1); please reopen.
```
debian:exit-assert-src james% ./configure --disable-native-codegeneration
[...]
debian:exit-assert-src james% make
[...]
debian:exit-assert-src james% for i in `seq 1 100`; do ./poly < /dev/null; done
[...]
Poly/ML 5.6 Release (Git version v5.6-228-g1e230f1)
poly: processes.cpp:712: virtual void Processes::ThreadExit(TaskData*): Assertion `index < taskArraySize && taskArray[index] == taskData' failed.
[...]
```

**Comment by jrtc27** [comment] 2016-04-12 16:41
I'm also seeing an occasional
```
Poly/ML 5.6 Release (Git version v5.6-228-g1e230f1)
pure virtual method called
terminate called without an active exception
```
which may or may not be related.

**Comment by jrtc27** [comment] 2016-04-12 21:11
I believe this is the race condition (or similar; I'm sure this is enough to make the details obvious to you). The key problem is detailed in 2, whatever the actual race is.

1. `IntTaskData::InterruptCode` is called
2. `itd->interrupt_requested` is set to true ***which is at the same address as `itd->threadExited` because `HAVE_PTHREAD` is not defined when `processes.h` is included by `interpret.cpp` so `interpret.cpp` sees `TaskData` as missing `threadExited`***
3. `BeginRootThread` sees the thread as killed, deletes its task data and nulls it out in `taskArray`
4. The poor thread reaches the assertion in ThreadExit and it's already been removed from `taskArray`
